// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOQPBUdkQhp1H_4g7dzFJlXQDpl2FShR0',
    appId: '1:1099239240888:web:064a65d3f270e89dcb704d',
    messagingSenderId: '1099239240888',
    projectId: 'kiko-mobile-application',
    authDomain: 'kiko-mobile-application.firebaseapp.com',
    storageBucket: 'kiko-mobile-application.firebasestorage.app',
    measurementId: 'G-XKMKX7L4HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHsGWnQTGTpd27tT7bss7pZSZ0P0A6OfU',
    appId: '1:1099239240888:android:9d6f40728064f31fcb704d',
    messagingSenderId: '1099239240888',
    projectId: 'kiko-mobile-application',
    storageBucket: 'kiko-mobile-application.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOQPBUdkQhp1H_4g7dzFJlXQDpl2FShR0',
    appId: '1:1099239240888:web:a6b99a87ec4d4b05cb704d',
    messagingSenderId: '1099239240888',
    projectId: 'kiko-mobile-application',
    authDomain: 'kiko-mobile-application.firebaseapp.com',
    storageBucket: 'kiko-mobile-application.firebasestorage.app',
    measurementId: 'G-L59Z5W94R2',
  );
}